// Package generators provides language-specific code generation
// implementations for the IncludeKit Universal Format.
//
// Each generator implements the Generator interface and is responsible
// for producing production types and testkit utilities for its target language.
package generators

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/bold-minds/ik-spec/codegen/internal/parser"
	"github.com/bold-minds/ik-spec/codegen/internal/templates"
)

type TypeScriptGenerator struct{}

func (g *TypeScriptGenerator) Generate(s *parser.Schema, outputDir string) error {
	// Generate production types using json-schema-to-typescript
	if err := g.generateTypes(s, outputDir); err != nil {
		return fmt.Errorf("failed to generate types: %w", err)
	}

	// Generate testkit using Go templates
	if err := g.generateTestkit(s, outputDir); err != nil {
		return fmt.Errorf("failed to generate testkit: %w", err)
	}

	return nil
}

func (g *TypeScriptGenerator) generateTypes(s *parser.Schema, outputDir string) error {
	// Validate and clean output directory
	outputDir = filepath.Clean(outputDir)
	if strings.Contains(outputDir, "..") {
		return fmt.Errorf("invalid output directory (directory traversal detected): %s", outputDir)
	}

	typesDir := filepath.Join(outputDir, "ts", "types")
	if err := os.MkdirAll(typesDir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	outputFile := filepath.Join(typesDir, "index.d.ts")

	// Check if npx is available
	if _, err := exec.LookPath("npx"); err != nil {
		return fmt.Errorf("npx not found - Node.js/npm required for TypeScript generation: %w", err)
	}

	// Validate schema path before using
	schemaPath := filepath.Clean(s.Path)
	if !filepath.IsAbs(schemaPath) {
		var err error
		schemaPath, err = filepath.Abs(schemaPath)
		if err != nil {
			return fmt.Errorf("failed to resolve schema path: %w", err)
		}
	}
	if strings.Contains(schemaPath, "..") {
		return fmt.Errorf("invalid schema path (directory traversal detected): %s", schemaPath)
	}

	// Call json-schema-to-typescript via npx
	cmd := exec.Command("npx", "--yes",
		"json-schema-to-typescript",
		schemaPath,
		"-o", outputFile,
		"--bannerComment", "",
		"--unreachableDefinitions",
		"--additionalProperties", "false",
	)

	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("json-schema-to-typescript failed: %w\nOutput: %s", err, output)
	}

	// Add custom header with dynamic version
	if err := prependHeader(outputFile, s.Path, s.Version); err != nil {
		return err
	}

	return nil
}

func (g *TypeScriptGenerator) generateTestkit(s *parser.Schema, outputDir string) error {
	// Output directory already validated in generateTypes
	testkitDir := filepath.Join(outputDir, "ts", "tests", "src")
	if err := os.MkdirAll(testkitDir, 0755); err != nil {
		return fmt.Errorf("failed to create testkit directory: %w", err)
	}

	// Generate validators.ts with dynamic schema path
	if err := templates.WriteTypeScriptValidators(testkitDir, s.Path); err != nil {
		return fmt.Errorf("failed to write validators: %w", err)
	}

	// Generate canonicalize.ts
	if err := templates.WriteTypeScriptCanonicalize(testkitDir); err != nil {
		return fmt.Errorf("failed to write canonicalize: %w", err)
	}

	// Generate shapeId.ts
	if err := templates.WriteTypeScriptShapeId(testkitDir); err != nil {
		return fmt.Errorf("failed to write shapeId: %w", err)
	}

	// Generate index.ts
	if err := templates.WriteTypeScriptIndex(testkitDir); err != nil {
		return fmt.Errorf("failed to write index: %w", err)
	}

	return nil
}

func (g *TypeScriptGenerator) Language() string {
	return "TypeScript"
}

func (g *TypeScriptGenerator) NeedsExternal() bool {
	return true // Needs npx/npm
}

func prependHeader(filepath, schemaPath, version string) error {
	content, err := os.ReadFile(filepath)
	if err != nil {
		return err
	}

	schemaFile := schemaPath
	if strings.Contains(schemaPath, "/") {
		schemaFile = schemaPath[strings.LastIndex(schemaPath, "/")+1:]
	}

	header := fmt.Sprintf(`/**
 * IncludeKit Universal Format v%s
 * Auto-generated from schema/%s
 * DO NOT EDIT - This file is automatically generated
 */

`, version, schemaFile)

	return os.WriteFile(filepath, []byte(header+string(content)), 0644)
}
