# Language labels
- name: typescript
  color: '3178c6'
  description: TypeScript related changes

- name: go
  color: '00ADD8'
  description: Go related changes

# Type labels
- name: bug
  color: 'd73a4a'
  description: Something isn't working

- name: enhancement
  color: 'a2eeef'
  description: New feature or request

- name: documentation
  color: '0075ca'
  description: Improvements or additions to documentation

- name: question
  color: 'd876e3'
  description: Further information is requested

# Priority labels
- name: priority/critical
  color: 'b60205'
  description: Critical priority

- name: priority/high
  color: 'ff9800'
  description: High priority

- name: priority/medium
  color: 'ffeb3b'
  description: Medium priority

- name: priority/low
  color: '4caf50'
  description: Low priority

# Status labels
- name: needs-triage
  color: 'fbca04'
  description: Needs triage

- name: work-in-progress
  color: 'fbca04'
  description: Work in progress

- name: blocked
  color: 'b60205'
  description: Blocked by another issue or PR

- name: stale
  color: 'eeeeee'
  description: Marked as stale due to inactivity

# Area labels
- name: schema
  color: '1d76db'
  description: Changes to the JSON schema

- name: codegen
  color: '5319e7'
  description: Code generation related

- name: tests
  color: '0e8a16'
  description: Test-related changes

- name: ci/cd
  color: '000000'
  description: CI/CD pipeline changes

# Special labels
- name: breaking-change
  color: 'b60205'
  description: Introduces breaking changes

- name: security
  color: 'b60205'
  description: Security-related issue

- name: good-first-issue
  color: '7057ff'
  description: Good for newcomers

- name: help-wanted
  color: '008672'
  description: Extra attention is needed

- name: duplicate
  color: 'cfd3d7'
  description: This issue or pull request already exists

- name: invalid
  color: 'e4e669'
  description: This doesn't seem right

- name: wontfix
  color: 'ffffff'
  description: This will not be worked on

# Size labels (auto-added by workflow)
- name: size/XS
  color: '0e8a16'
  description: Extra small PR (0-10 lines)

- name: size/S
  color: '4caf50'
  description: Small PR (11-100 lines)

- name: size/M
  color: 'ffeb3b'
  description: Medium PR (101-250 lines)

- name: size/L
  color: 'ffa500'
  description: Large PR (251-500 lines)

- name: size/XL
  color: 'ff9800'
  description: Extra large PR (501-1000 lines)

- name: size/XXL
  color: 'b60205'
  description: Extra extra large PR (1000+ lines)
