name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Import the package...
        2. Create a Statement with...
        3. Call computeShapeId()...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happens...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: If possible, provide a minimal code sample that reproduces the issue
      render: typescript
      placeholder: |
        import { Statement } from '@includekit/spec';
        
        const statement: Statement = {
          // Your code here
        };

  - type: dropdown
    id: language
    attributes:
      label: Language
      description: Which language are you using?
      options:
        - TypeScript
        - Go
        - Both
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      description: Which version of includekit-spec are you using?
      placeholder: "e.g., 0.1.0"
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version (if TypeScript)
      placeholder: "e.g., 20.9.0"

  - type: input
    id: go-version
    attributes:
      label: Go Version (if Go)
      placeholder: "e.g., 1.22.0"

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "e.g., macOS 14.0, Ubuntu 22.04, Windows 11"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, logs, etc.)
      placeholder: Any additional information...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the information requested above
          required: true
        - label: I have read the [Contributing Guidelines](https://github.com/bold-minds/includekit-spec/blob/main/CONTRIBUTING.md)
          required: true
