name: 💡 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What is your use case?
      placeholder: I'm always frustrated when... / I need to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work? Be as specific as possible.
      placeholder: |
        I would like to be able to...
        
        Example API:
        ```typescript
        // Your proposed API here
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or features have you considered?
      placeholder: I considered... but that wouldn't work because...
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How would this feature impact the project?
      options:
        - Breaking change (requires major version bump)
        - Additive change (requires minor version bump)
        - Internal improvement (patch version)
        - Not sure
    validations:
      required: true

  - type: dropdown
    id: language
    attributes:
      label: Language
      description: Which language implementation would this affect?
      options:
        - TypeScript
        - Go
        - Both
        - Language-agnostic (schema level)
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples from Other ORMs
      description: Are there similar features in other ORMs (Prisma, TypeORM, GORM, etc.)?
      placeholder: |
        Prisma does this with...
        GORM supports...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples
      placeholder: Any additional information...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: This feature aligns with the goals of IncludeKit
          required: true
        - label: I have read the [Contributing Guidelines](https://github.com/bold-minds/includekit-spec/blob/main/CONTRIBUTING.md)
          required: true
        - label: I am willing to contribute to implementing this feature
          required: false
