/**
 * IncludeKit Universal Format v0.1
 * Auto-generated from schema/v0-1-0.json
 * DO NOT EDIT - This file is automatically generated
 */

export interface IncludeKitUniversalFormatV01 {
  Statement?: Statement;
  Mutation?: Mutation;
  Dependencies?: Dependencies;
}
/**
 * This interface was referenced by `IncludeKitUniversalFormatV01`'s JSON-Schema
 * via the `definition` "Statement".
 */
export interface Statement {
  query?: Query;
  pagination?: Pagination;
  group_by?: string[];
  having?: Filter;
  includes?: Include[];
  /**
   * Diagnostic only; excluded from canonicalization
   */
  orm_version?: string;
  /**
   * Diagnostic only; excluded from canonicalization
   */
  sdk_version?: string;
}
/**
 * This interface was referenced by `IncludeKitUniversalFormatV01`'s JSON-Schema
 * via the `definition` "Query".
 */
export interface Query {
  model: string;
  fields?: string[];
  where?: Filter;
  order_by?: OrderBy[];
  limit?: number;
  offset?: number;
  distinct?: string[];
}
/**
 * This interface was referenced by `IncludeKitUniversalFormatV01`'s JSON-Schema
 * via the `definition` "Filter".
 */
export interface Filter {
  and?: Filter[];
  or?: Filter[];
  not?: Filter;
  conditions?: Condition[];
}
/**
 * This interface was referenced by `IncludeKitUniversalFormatV01`'s JSON-Schema
 * via the `definition` "Condition".
 */
export interface Condition {
  field: string;
  /**
   * Optional path for nested field access (e.g., ['address', 'city'])
   */
  field_path?: string[];
  op:
    | (
        | "eq"
        | "ne"
        | "in"
        | "notIn"
        | "isNull"
        | "gt"
        | "gte"
        | "lt"
        | "lte"
        | "between"
        | "contains"
        | "startsWith"
        | "endsWith"
        | "like"
        | "ilike"
        | "regex"
        | "has"
        | "hasSome"
        | "hasEvery"
        | "jsonContains"
        | "lenEq"
        | "lenGt"
        | "lenLt"
        | "exists"
      )
    | string;
  value?: unknown;
  /**
   * @deprecated
   * Deprecated: use field_path instead
   */
  path?: string[];
}
/**
 * This interface was referenced by `IncludeKitUniversalFormatV01`'s JSON-Schema
 * via the `definition` "OrderBy".
 */
export interface OrderBy {
  field: string;
  descending?: boolean;
  nulls_first?: boolean;
  case_sensitive?: boolean;
}
/**
 * This interface was referenced by `IncludeKitUniversalFormatV01`'s JSON-Schema
 * via the `definition` "Pagination".
 */
export interface Pagination {
  first?: number;
  last?: number;
  after?: string;
  before?: string;
}
/**
 * This interface was referenced by `IncludeKitUniversalFormatV01`'s JSON-Schema
 * via the `definition` "Include".
 */
export interface Include {
  query?: Query;
  kind?: "some" | "every" | "none";
  includes?: Include[];
}
/**
 * This interface was referenced by `IncludeKitUniversalFormatV01`'s JSON-Schema
 * via the `definition` "Mutation".
 */
export interface Mutation {
  tx_id?: string;
  changes: Change[];
}
/**
 * This interface was referenced by `IncludeKitUniversalFormatV01`'s JSON-Schema
 * via the `definition` "Change".
 */
export interface Change {
  model: string;
  action: "insert" | "update" | "delete";
  sets?: KV[];
  where?: Filter;
}
/**
 * This interface was referenced by `IncludeKitUniversalFormatV01`'s JSON-Schema
 * via the `definition` "KV".
 */
export interface KV {
  field: string;
  value: unknown;
}
/**
 * This interface was referenced by `IncludeKitUniversalFormatV01`'s JSON-Schema
 * via the `definition` "Dependencies".
 */
export interface Dependencies {
  shape_id: string;
  records: {
    [k: string]: string[];
  };
  filters: Filter[];
  includes: Include[];
  last_row?: PaginationBoundary;
  group_by?: {
    keys: string[];
    values: {
      [k: string]: unknown;
    }[];
  };
}
/**
 * This interface was referenced by `IncludeKitUniversalFormatV01`'s JSON-Schema
 * via the `definition` "PaginationBoundary".
 */
export interface PaginationBoundary {
  order_by: OrderBy[];
  /**
   * Field values of the last included row
   */
  row: {
    [k: string]: unknown;
  };
  cursor?: KV;
}
