/**
 * IncludeKit Universal Format v0.1
 * Auto-generated from schema/v0-1-0.json
 * DO NOT EDIT - This file is automatically generated
 */

/**
 * Scalar supported in filters/values
 *
 * This interface was referenced by `IncludeKitUniversalFormatV01`'s JSON-Schema
 * via the `definition` "Scalar".
 */
export type Scalar =
  | string
  | number
  | boolean
  | null
  | {
      json: unknown;
    };
/**
 * This interface was referenced by `IncludeKitUniversalFormatV01`'s JSON-Schema
 * via the `definition` "WriteChange".
 */
export type WriteChange =
  | {
      after: {
        [k: string]: Scalar;
      };
      id: string;
      model: string;
      op: "create";
    }
  | {
      after: {
        [k: string]: Scalar;
      };
      before: {
        [k: string]: Scalar;
      };
      id: string;
      model: string;
      op: "update";
    }
  | {
      before: {
        [k: string]: Scalar;
      };
      id: string;
      model: string;
      op: "delete";
    }
  | LinkChange;
/**
 * This interface was referenced by `IncludeKitUniversalFormatV01`'s JSON-Schema
 * via the `definition` "LinkChange".
 */
export type LinkChange =
  | {
      childId: string;
      childModel: string;
      kind: "link";
      parentId: string;
      parentModel: string;
      relation: string;
    }
  | {
      childId: string;
      childModel: string;
      kind: "unlink";
      parentId: string;
      parentModel: string;
      relation: string;
    };

export interface IncludeKitUniversalFormatV01 {
  Dependencies?: Dependencies;
  MutationEvent?: MutationEvent;
  QueryShape?: QueryShape;
}
/**
 * This interface was referenced by `IncludeKitUniversalFormatV01`'s JSON-Schema
 * via the `definition` "Dependencies".
 */
export interface Dependencies {
  filterBounds: FilterSpec[];
  groups?: {
    keys: string[];
    values: {
      [k: string]: Scalar;
    }[];
  };
  records: {
    [k: string]: string[];
  };
  relationBounds: RelationFilterBound[];
  shapeId: string;
  topN?: SortThreshold;
}
/**
 * This interface was referenced by `IncludeKitUniversalFormatV01`'s JSON-Schema
 * via the `definition` "FilterSpec".
 */
export interface FilterSpec {
  and?: FilterSpec[];
  atoms?: FilterAtom[];
  not?: FilterSpec;
  or?: FilterSpec[];
}
/**
 * This interface was referenced by `IncludeKitUniversalFormatV01`'s JSON-Schema
 * via the `definition` "FilterAtom".
 */
export interface FilterAtom {
  field: string;
  op:
    | (
        | "eq"
        | "ne"
        | "in"
        | "notIn"
        | "isNull"
        | "gt"
        | "gte"
        | "lt"
        | "lte"
        | "between"
        | "contains"
        | "startsWith"
        | "endsWith"
        | "like"
        | "ilike"
        | "regex"
        | "has"
        | "hasSome"
        | "hasEvery"
        | "jsonContains"
        | "lenEq"
        | "lenGt"
        | "lenLt"
        | "exists"
      )
    | string;
  path?: string[];
  value?:
    | Scalar
    | Scalar[]
    | {
        max: Scalar;
        min: Scalar;
      }
    | {
        flags?: string;
        pattern: string;
      };
}
/**
 * This interface was referenced by `IncludeKitUniversalFormatV01`'s JSON-Schema
 * via the `definition` "RelationFilterBound".
 */
export interface RelationFilterBound {
  kind: "some" | "every" | "none";
  relation: string;
  where?: FilterSpec;
}
/**
 * This interface was referenced by `IncludeKitUniversalFormatV01`'s JSON-Schema
 * via the `definition` "SortThreshold".
 */
export interface SortThreshold {
  boundary: {
    [k: string]: Scalar;
  };
  orderBy: OrderBySpec[];
  tieBreaker?: {
    field: string;
    value: Scalar;
  };
}
/**
 * This interface was referenced by `IncludeKitUniversalFormatV01`'s JSON-Schema
 * via the `definition` "OrderBySpec".
 */
export interface OrderBySpec {
  collation?: "ci" | "cs";
  direction: "asc" | "desc";
  field: string;
  nulls?: "first" | "last";
}
/**
 * This interface was referenced by `IncludeKitUniversalFormatV01`'s JSON-Schema
 * via the `definition` "MutationEvent".
 */
export interface MutationEvent {
  changes: WriteChange[];
  txId?: string;
}
/**
 * This interface was referenced by `IncludeKitUniversalFormatV01`'s JSON-Schema
 * via the `definition` "QueryShape".
 */
export interface QueryShape {
  adapterVersion?: string;
  cursor?: CursorSpec | null;
  distinct?: string[];
  groupBy?: string[];
  having?: FilterSpec | null;
  include?: {
    [k: string]: IncludeSpec;
  };
  model: string;
  orderBy?: OrderBySpec[];
  /**
   * diagnostic only; excluded from canonicalization
   */
  orm?: "prisma" | "typeorm" | "sequelize" | "gorm" | "efcore" | "hibernate" | "django" | "sqlalchemy" | "drizzle";
  select?: string[];
  skip?: number;
  take?: number;
  where?: FilterSpec;
}
/**
 * This interface was referenced by `IncludeKitUniversalFormatV01`'s JSON-Schema
 * via the `definition` "CursorSpec".
 */
export interface CursorSpec {
  before?: boolean;
  fields: string[];
  values: Scalar[];
}
/**
 * This interface was referenced by `IncludeKitUniversalFormatV01`'s JSON-Schema
 * via the `definition` "IncludeSpec".
 */
export interface IncludeSpec {
  distinct?: string[];
  include?: {
    [k: string]: IncludeSpec;
  };
  orderBy?: OrderBySpec[];
  relationFilter?: RelationFilterBound[];
  select?: string[];
  separateLoad?: boolean;
  skip?: number;
  take?: number;
  where?: FilterSpec;
}
